apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    solvers:
      - http01:
          ingress:
            class: nginx
    email: ye5400qc@my.century.edu
    privateKeySecretRef:
      name: letsencrypt-dev
    server: https://acme-v02.api.letsencrypt.org/directory
